# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage
lang: en

# Timezone (optional)
timezone:

# jekyll-seo-tag settings
title: Hope Njoki Nyambura
tagline: Full-Stack Developer | Cybersecurity Enthusiast | Data-Driven Innovator
description: >-
  Portfolio of Hope Njoki Nyambura — Full-Stack Developer with expertise in web development, cybersecurity, and data analysis. Showcasing projects, lab challenges, resume, and certifications.

url: "https://defhopeee.github.io"

github:
  username: defhopeee

twitter:
  username: twitter_username

social:
  name: Hope Njoki Nyambura
  email: defhopeee@gmail.com
  links:
    - https://twitter.com/username
    - https://github.com/defhopeee
    - https://www.linkedin.com/in/hope-nyambura-787a2b367

webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

analytics:
  google:
    id:
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

pageviews:
  provider:

theme_mode:

cdn:

avatar:

social_preview_image:

toc: true

comments:
  provider:
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

assets:
  self_host:
    enabled:
    env:

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

paginate: 10
baseurl: ""

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

# ----------------- jekyll-archives disabled to avoid missing layouts -----------------
# jekyll-archives:
#   enabled: [categories, tags]
#   layouts:
#     category: category
#     tag: tag
#   permalinks:
#     tag: /tags/:name/
#     category: /categories/:name/
